### ISSUE TITLE
OSError: Can't load config for 'EleutherAI/gpt-j-6B'.

### ISSUE THREAD

**Issue by ElJaviLuki** [jarrellmark/chatgpt-j#1]
## Issue Summary
I encountered an error while trying to use the transformers package in Python. The error message I received is:

```OSError: Can't load config for 'EleutherAI/gpt-j-6B'. Make sure that:

- 'EleutherAI/gpt-j-6B' is a correct model identifier listed on 'https://huggingface.co/models'
  (make sure 'EleutherAI/gpt-j-6B' is not a path to a local directory with something else, in that case)

- or 'EleutherAI/gpt-j-6B' is the correct path to a directory containing a config.json file
```

## Steps to Reproduce:
1. Just execute the Colab.

## Expected Behavior:
I expected the transformers package to be able to load the configuration file for the specified model.

## Actual Behavior:
The package was unable to load the configuration file and raised an OSError.

**Comment by DaveW111** [comment]
Same here. This discussion on HuggingFace seems to be the same issue, but im too much of a noob to interpret it: https://discuss.huggingface.co/t/how-to-get-eleutherai-gpt-j-6b-working/9427

**Comment by ElJaviLuki** [comment]
Hi @DaveW111 , I eventually fixed this, take a look at this [pull request #2](https://github.com/jarrellmark/chatgpt-j/pull/2) .

**Comment by DaveW111** [comment]
Thanks, I just discovered the same thing but you beat me to it! :)

**Comment by rahm-hopkins** [comment]
> Hi @DaveW111 , I eventually fixed this, take a look at this [pull request #2](https://github.com/jarrellmark/chatgpt-j/pull/2) .

Wow, thank you for figuring this out!
